### ISSUE TITLE
level=error msg="update config error: get packet-forwarder config error: get configuration error: rpc error: code = Unimplemented desc = unknown service gw.Gateway

### ISSUE THREAD

**Issue by bauand** [brocaar/lora-channel-manager#2]

**Comment by brocaar** [comment]
Were you already able to fix your issue? I expect that you're able to fix this by updating LoRa Server to the latest version.

**Comment by bauand** [comment]
Hi, i have not used lora-gateway-config since my (very first github) issue. I will update the lora-server software on my system and let you know. Thanks for your response!

**Comment by brocaar** [comment]
The LoRa Channel Manager feature has been merged into the LoRa Gateway Bridge. The LoRa Channel Manager component is now deprecated.
