### ISSUE TITLE
Can't set discontinuous channel

### ISSUE THREAD

**Issue by ckt1010** [brocaar/lora-channel-manager#4]
### Is this a bug or a feature request?
Bug
### What did you expect?
set channel 0,1,2,3,4,5,6,20 in lora-app-server, and gateway will change to this channel automatically.
### What happened?
Last channel: 20 will set as radio 0, log in packet-forward like below:

> 135639 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: radio 0 enabled (type SX1255), center frequency 470700000, RSSI offset -176.000000, tx enabled 1, tx_notch_freq 0
> 135640 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: radio 1 enabled (type SX1255), center frequency 471700000, RSSI offset -176.000000, tx enabled 0, tx_notch_freq 0
> 135641 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 0>  radio 0, IF -400000 Hz, 125 kHz bw, SF 7 to 12
> 135642 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 1>  radio 0, IF -200000 Hz, 125 kHz bw, SF 7 to 12
> 135643 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 2>  radio 0, IF 0 Hz, 125 kHz bw, SF 7 to 12
> 135644 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 3>  radio 0, IF 200000 Hz, 125 kHz bw, SF 7 to 12
> 135645 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 4>  radio 0, IF 400000 Hz, 125 kHz bw, SF 7 to 12
> 135646 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 5>  radio 1, IF -400000 Hz, 125 kHz bw, SF 7 to 12
> 135647 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 6>  radio 1, IF -200000 Hz, 125 kHz bw, SF 7 to 12
> 135648 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: INFO: Lora multi-SF channel 7>  radio 0, IF 1600000 Hz, 125 kHz bw, SF 7 to 12
> 135649 Sep  7 02:19:48 rhf2s001 lora_pkt_fwd[16561]: ERROR: invalid configuration for Lora multi-SF channel 7

### What version are your using?
git harsh: 66ddba1fba60747087293e7b2c9e00d40e7fd87d
### How can your issue be reproduced?
try to set discontinuous channel in "channel configuration, like:0,1,2,3,4,5,6,20
### Could you share your log output?
this is my global_conf.json:

> `{"SX1301_conf":{"chan_FSK":{"bandwidth":0,"datarate":0,"enable":false,"if":0,"radio":0},"chan_Lora_std":{"bandwidth":0,"enable":false,"if":0,"radio":0,"spread_factor":0},"chan_multiSF_0":{"enable":true,"if":-400000,"radio":0},"chan_multiSF_1":{"enable":true,"if":-200000,"radio":0},"chan_multiSF_2":{"enable":true,"if":0,"radio":0},"chan_multiSF_3":{"enable":true,"if":200000,"radio":0},"chan_multiSF_4":{"enable":true,"if":400000,"radio":0},"chan_multiSF_5":{"enable":true,"if":-400000,"radio":1},"chan_multiSF_6":{"enable":true,"if":-200000,"radio":1},"chan_multiSF_7":{"enable":true,"if":1600000,"radio":0},"clksrc":1,"lorawan_public":true,"radio_0":{"enable":true,"freq":470700000,"rssi_offset":-176,"tx_enable":true,"tx_freq_max":510000000,"tx_freq_min":470000000,"type":"SX1255"},"radio_1":{"enable":true,"freq":471700000,"rssi_offset":-176,"tx_enable":false,"type":"SX1255"},"tx_lut_0":{"dig_gain":0,"mix_gain":8,"pa_gain":0,"rf_power":-1},"tx_lut_1":{"dig_gain":0,"mix_gain":10,"pa_gain":0,"rf_power":2},"tx_lut_10":{"dig_gain":0,"mix_gain":9,"pa_gain":2,"rf_power":19},"tx_lut_11":{"dig_gain":0,"mix_gain":9,"pa_gain":0,"rf_power":20},"tx_lut_12":{"dig_gain":0,"mix_gain":11,"pa_gain":2,"rf_power":21},"tx_lut_13":{"dig_gain":0,"mix_gain":13,"pa_gain":2,"rf_power":22},"tx_lut_14":{"dig_gain":0,"mix_gain":9,"pa_gain":3,"rf_power":23},"tx_lut_15":{"dig_gain":0,"mix_gain":11,"pa_gain":3,"rf_power":24},"tx_lut_2":{"dig_gain":0,"mix_gain":12,"pa_gain":0,"rf_power":4},"tx_lut_3":{"dig_gain":0,"mix_gain":8,"pa_gain":1,"rf_power":9},"tx_lut_4":{"dig_gain":0,"mix_gain":10,"pa_gain":1,"rf_power":11},"tx_lut_5":{"dig_gain":0,"mix_gain":10,"pa_gain":1,"rf_power":12},"tx_lut_6":{"dig_gain":0,"mix_gain":12,"pa_gain":1,"rf_power":13},"tx_lut_7":{"dig_gain":0,"mix_gain":13,"pa_gain":1,"rf_power":14},"tx_lut_8":{"dig_gain":0,"mix_gain":15,"pa_gain":1,"rf_power":15},"tx_lut_9":{"dig_gain":0,"mix_gain":8,"pa_gain":2,"rf_power":17}},"gateway_conf":{"forward_crc_disabled":false,"forward_crc_error":false,"forward_crc_valid":true,"gateway_ID":"0000b827eb41e673","gps_tty_path":"/dev/tty","keepalive_interval":10,"push_timeout_ms":100,"serv_port_down":1700,"serv_port_up":1700,"server_address":"192.168.10.172","stat_interval":30}}`

**Comment by brocaar** [comment]
Did you confirm that your channel-plan fits within the bandwidth of your gateway radios? For 125KHz channels the bandwidth of each radio is 0.925MHz.

I did not do the math, but I don't think you'll be able to fit your channel-plan on both radios (hence the error).

**Comment by brocaar** [comment]
The LoRa Channel Manager feature has been merged into the LoRa Gateway Bridge. The LoRa Channel Manager component is now deprecated.
